name: test_utils_for_perception
description: Helper classes for testing apps that use astro.
version: 0.0.0-a1
publish_to: none

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_test:
    sdk: flutter
  
  core_of_perception:
    git: https://github.com/enspyrco/core_of_perception
  types_for_perception:
    git: https://github.com/enspyrco/types_for_perception
  locator_for_perception:
    git: https://github.com/enspyrco/locator_for_perception
  error_handling_for_perception:
    git: https://github.com/enspyrco/error_handling_for_perception

  types_for_auth:
    git: https://github.com/enspyrco/types_for_auth
  json_utils:
    git: https://github.com/enspyrco/json_utils

dev_dependencies:
  enspyr_lints:
    git: https://github.com/enspyrco/enspyr_lints
