name: test_utils_for_perception
description: Helper classes for testing apps that use astro.
version: 0.0.0-a1
publish_to: none

environment:
  sdk: '>=3.0.1 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  flutter_test:
    sdk: flutter
  
  core_of_perception: ^0.0.0-a1
  locator_for_perception: ^0.0.0-a1
  types_for_perception: ^0.0.0-a1

dev_dependencies:
  enspyr_lints: ^0.0.0-a1
  build_runner: ^2.4.5
  builders_for_perception: ^0.0.0-a1